### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by jhonathan282** [H4ckd4ddy/bypass-sentry-safe#4]
Salut, j'aimerais reproduire ton attaque sur sentry safe, Je veux savoir quels sont les composants dont j'ai besoin pour que je puisse le reproduire? ou un schéma? merci

**Comment by H4ckd4ddy** [comment]
Hello,
Désolé pour le délai de réponse 😅.
Toutes les infos sont dans le repo.
Le plus simple est d'utiliser un Arduino ou un Flipper zero
Cordialement
